# Configuration for ML Trading Strategy

# --- Data Settings ---
data_directory: "data"

# --- Data Download Settings (Used by download_data.py) ---
# API key is read from environment variable CYBOTRADE_API_KEY

# Define metrics and candles to download
# Structure: {source: [ {path: "endpoint_path", params: {key: value, ...}}, ... ]}
# VERIFY paths and parameter values (exchange, window, i, a, symbol, interval) against cybotrade.rs docs!
metrics_to_download:
  cryptoquant:
    - path: "btc/exchange-flows/inflow"
      params: { exchange: "binance", window: "day" }
    - path: "btc/market-data/funding-rates"
      params: { exchange: "binance", window: "day" }
  glassnode:
    - path: "addresses/active_count"
      params: { a: "BTC", i: "24h" }
    - path: "transactions/count"
      params: { a: "BTC", i: "24h" }
  coinglass:
    - path: "futures/openInterest/ohlc-history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1d" }
    - path: "futures/globalLongShortAccountRatio/history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1d" }
  # Candle source uses a slightly different structure if needed, or can follow path/params
  candles:
     - source_override: "bybit-linear"
       path: "candle"
       params: { symbol: "BTCUSDT", interval: "1d"}


# Time periods for downloading data (Unix timestamp in milliseconds)
# Backtest Period
backtest_start_time_ms: 1609459200000     # Jan 1 2021
backtest_end_time_ms: 1704067199000       # Dec 31 2023
# Forward Test Period
forwardtest_start_time_ms: 1704067200000  # Jan 1 2024
forwardtest_end_time_ms: 1735689600000    # Jan 1 2025

# # Backtest Period
# # backtest_start_time_ms: 1609459200000     # Jan 1 2021
# backtest_start_time_ms: 1577836800000     # Jan 1 2020
# backtest_end_time_ms: 1672531199000       # Dec 31 2022
# # Forward Test Period
# forwardtest_start_time_ms: 1672531200000  # Jan 1 2023
# forwardtest_end_time_ms: 1735689599000    # Dec 31 2024

# Data Preprocessing Settings
# Define a dictionary of data files to load
# eg:
# [KEY] -- name of the dataset loaded, can be any name
# [file_base] -- base name of the file to load, without these extensions (_backtest, _forwardtest, .csv)
# [original_columns] -- list of columns to load from the file (sometimes files have value or v, so we need to cover the possibilities)
# [target_column] -- name of the column to use in the final dataset (rename the original column to this name)
#
# Example:
# cryptoquant_funding:
#   file_base: "cryptoquant_btc_market-data_funding-rates"
#   original_columns: ["fundingRate", "value"]
#   target_column: "cryptoquant_funding_rate"

data_files:
  candles:
    file_base: "bybit-linear_candle"
  cryptoquant_inflow:
    file_base: "cryptoquant_btc_exchange-flows_inflow"
    original_columns: ["value"]
    target_column: "cryptoquant_inflow_value"
  cryptoquant_funding:
    file_base: "cryptoquant_btc_market-data_funding-rates"
    original_columns: ["fundingRate", "value"]
    target_column: "cryptoquant_funding_rate"
  glassnode_active:
    file_base: "glassnode_addresses_active_count"
    original_columns: ["value", "v"]
    target_column: "glassnode_active_value"
  glassnode_tx:
    file_base: "glassnode_transactions_count"
    original_columns: ["value", "v"]
    target_column: "glassnode_tx_value"
  coinglass_oi:
    file_base: "coinglass_futures_openInterest_ohlc-history"
    original_columns: ["openInterest", "c"]
    target_column: "coinglass_oi_value"
  coinglass_lsr:
    file_base: "coinglass_futures_globalLongShortAccountRatio_history"
    original_columns: ["longShortRatio", "value"]
    target_column: "coinglass_lsr_value"

# Features to use for HMM model training (should match target_column names above or engineered ones)

# Features to use for HMM model training (column names after data loading/preprocessing)
# Example - adjust based on actual columns and desired features
# Features to use for HMM model training (column names after data loading/preprocessing)
features:
  - "price_return"
  - "volatility"
  - "cryptoquant_funding_rate"
  # - "glassnode_active_value"
  # - "funding_rate_change"
  # - "active_addresses_change"
  - "cryptoquant_inflow_value"
  - "coinglass_oi_value"

# HMM Settings
min_hmm_states: 2
max_hmm_states: 5
# Options: "spherical", "diag", "full", "tied"
hmm_covariance_type: "diag"
hmm_iterations: 1000

# Trading Strategy Settings
trading_fee_percent: 0.0006

# Map HMM states to trading signals (0=Hold, 1=Buy, -1=Sell)
signal_map:
  0: 1
  1: -1
  2: 0
  3: 1
  4: 1

# Backtest/Forward Test Execution Settings
# Options: "backtest", "forwardtest"
# run_mode: "backtest"
run_mode: "forwardtest"
