# Configuration for ML Trading Strategy

# --- Data Settings ---
data_directory: "data"

# --- Data Download Settings (Used by download_data.py) ---
# API key is read from environment variable CYBOTRADE_API_KEY

# Define metrics and candles to download
# Structure: {source: [ {path: "endpoint_path", params: {key: value, ...}}, ... ]}
# VERIFY paths and parameter values (exchange, window, i, a, symbol, interval) against cybotrade.rs docs!
metrics_to_download:
  cryptoquant:
    - path: "btc/exchange-flows/inflow"
      params: { exchange: "binance", window: "day" }
    - path: "btc/market-data/funding-rates"
      params: { exchange: "binance", window: "day" }
  glassnode:
    - path: "addresses/active_count"
      params: { a: "BTC", i: "24h" }
    - path: "transactions/count"
      params: { a: "BTC", i: "24h" }
  coinglass:
    - path: "futures/openInterest/ohlc-history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1d" }
    - path: "futures/globalLongShortAccountRatio/history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1d" }
  # Candle source uses a slightly different structure if needed, or can follow path/params
  candles:
     - source_override: "bybit-linear"
       path: "candle"
       params: { symbol: "BTCUSDT", interval: "1d"}


# Time periods for downloading data (Unix timestamp in milliseconds)
# Backtest Period
# backtest_start_time_ms: 1577836800000     # Jan 1 2020
backtest_start_time_ms: 1609459200000     # Jan 1 2021
backtest_end_time_ms: 1704067199000       # Dec 31 2023
# Forward Test Period
forwardtest_start_time_ms: 1704067200000  # Jan 1 2024
forwardtest_end_time_ms: 1735689600000    # Jan 1 2025

# Data Preprocessing Settings
# Define a dictionary of data files to load
# eg:
# [KEY] -- name of the dataset loaded, can be any name
# [file_base] -- base name of the file to load, without these extensions (_backtest, _forwardtest, .csv)
# [original_columns] -- list of columns to load from the file (sometimes files have value or v, so we need to cover the possibilities)
# [target_column] -- name of the column to use in the final dataset (rename the original column to this name)
#
# Example:
# cryptoquant_funding:
#   file_base: "cryptoquant_btc_market-data_funding-rates"
#   original_columns: ["fundingRate", "value"]
#   target_column: "cryptoquant_funding_rate"

data_files:
  candles:
    file_base: "bybit-linear_candle"
  cryptoquant_inflow:
    file_base: "cryptoquant_btc_exchange-flows_inflow"
    original_columns: ["value"]
    target_column: "cryptoquant_inflow_value"
  cryptoquant_funding:
    file_base: "cryptoquant_btc_market-data_funding-rates"
    original_columns: ["fundingRate", "value"]
    target_column: "cryptoquant_funding_rate"
  glassnode_active:
    file_base: "glassnode_addresses_active_count"
    original_columns: ["value", "v"]
    target_column: "glassnode_active_value"
  glassnode_tx:
    file_base: "glassnode_transactions_count"
    original_columns: ["value", "v"]
    target_column: "glassnode_tx_value"
  coinglass_oi:
    file_base: "coinglass_futures_openInterest_ohlc-history"
    original_columns: ["openInterest", "c"]
    target_column: "coinglass_oi_value"
  coinglass_lsr:
    file_base: "coinglass_futures_globalLongShortAccountRatio_history"
    original_columns: ["longShortRatio", "value"]
    target_column: "coinglass_lsr_value"

# Features to use for HMM model training (Candidate Pool for Selection)
features:
  # Price-based
  - "price_return"
  - "volatility_10d"
  # Funding Rate based
  - "cryptoquant_funding_rate" # Raw value
  - "funding_rate_change_1d"   # Daily change
  - "funding_rate_MA_5d"       # 5-day Moving Average
  # Active Addresses based
  # - "glassnode_active_value"     # Raw value
  # - "active_addresses_change_1d" # Daily pct change
  # Transaction based
  # - "glassnode_tx_value"         # Raw value
  # - "tx_count_MA_5d"             # 5-day Moving Average
  # Combined Activity/Tx based
  # - "active_addr_tx_ratio"       # Ratio Active/Tx
  # Inflow based
  - "cryptoquant_inflow_value"   # Raw value
  # - "inflow_vol_ratio"           # Ratio Inflow/Volume
  # Open Interest based
  - "coinglass_oi_value"         # Raw value (assuming it's the closing OI)
  # - "oi_change_1d"               # Daily pct change
  # Long/Short Ratio based (using the generic name from loading)
  # - "coinglass_lsr_generic"      # Raw value (assuming it's Long Account or Ratio)
  # - "lsr_MA_5d"                  # 5-day Moving Average

# HMM Settings
# Avoid going more than 6 states for HMM, as it can lead to overfitting
min_hmm_states: 3
max_hmm_states: 6
# Options: "spherical", "diag", "full", "tied"
hmm_covariance_type: "diag"
hmm_iterations: 1000
state_stability_threshold: 10

# Trading Strategy Settings
trading_fee_percent: 0.0006

# Map HMM states to trading signals (0=Do Nothing, 1=Buy, -1=Sell)
signal_map:
  0: -1   # Positive return, low vol
  1: -1  # Negative return, high vol
  2: -1   # Weak bearish consolidation
  3: -1   # Strong bullish momentum
  4: -1   # Mixed signals, high funding but negative price/OI
  5: -1   # Low vol consolidation

# Backtest/Forward Test Execution Settings
# Options: "backtest", "forwardtest"
# run_mode: "backtest"
# run_mode: "forwardtest"
