# Configuration for ML Trading Strategy

# --- Data Settings ---
data_directory: "data"

# --- Data Download Settings (Used by download_data.py) ---
# API key is read from environment variable CYBOTRADE_API_KEY

# Define metrics and candles to download
# Structure: {source: [ {path: "endpoint_path", params: {key: value, ...}}, ... ]}
# VERIFY paths and parameter values (exchange, window, i, a, symbol, interval) against cybotrade.rs docs!
metrics_to_download:
  cryptoquant:
    - path: "btc/exchange-flows/inflow" # Just the path
      params: { exchange: "binance", window: "hour" } # Source-specific params
    - path: "btc/market-data/funding-rates"
      params: { exchange: "binance", window: "hour" } # Example
  glassnode:
    - path: "addresses/active_count"
      params: { a: "BTC", i: "24h" } # Example: Daily interval
    - path: "transactions/count"
      params: { a: "BTC", i: "24h" } # Example: Daily interval
  coinglass:
    - path: "futures/openInterest/ohlc-history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1h" }
    - path: "futures/globalLongShortAccountRatio/history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1h" }
  candles: # Candle source uses a slightly different structure if needed, or can follow path/params
     # Option 1: Keep original topic string for candles if simpler? (Script needs adjustment)
     # - "bybit-linear|candle?symbol=BTCUSDT&interval=1h"
     # Option 2: Use path/params structure (Script needs adjustment to handle source correctly)
     - source_override: "bybit-linear" # Specify the source host part
       path: "candle"
       params: { symbol: "BTCUSDT", interval: "1h"}


# Time periods for downloading data (Unix timestamp in milliseconds)
# Backtest Period (3 years)
backtest_start_time_ms: 1609459200000     # Jan 1 2021
backtest_end_time_ms: 1704067199000       # Dec 31 2023
# Forward Test Period (3 years)
forwardtest_start_time_ms: 1704067200000  # Jan 1 2024
forwardtest_end_time_ms: 1735689600000    # Jan 1 2025

# --- ML Model & Strategy Settings (Used by main_strategy.py) ---
# ... (rest of the config remains the same, but update data_files based on new naming) ...
# Example: Update data_files based on path/params structure
data_files:
  candles: "bybit-linear_candle" # Simpler name now
  cryptoquant_inflow: "cryptoquant_btc_exchange-flows_inflow"
  cryptoquant_funding: "cryptoquant_btc_market-data_funding-rates"
  glassnode_active: "glassnode_addresses_active_count"
  glassnode_tx: "glassnode_transactions_count"
  coinglass_oi: "coinglass_futures_openInterest_ohlc-history"
  coinglass_lsr: "coinglass_futures_globalLongShortAccountRatio_history"

# Features to use for HMM model training (column names after data loading/preprocessing)
# Example - adjust based on actual columns and desired features
# Features to use for HMM model training (column names after data loading/preprocessing)
features:
  - "price_return"            # How much the price changed
  - "volatility"              # How volatile the price was
  - "cryptoquant_funding_rate"
  - "glassnode_active_value"
  - "cryptoquant_inflow_value"
  - "coinglass_oi_value"

# HMM Settings
hmm_states: 4 # Number of hidden states (e.g., 0=Bear/Consolidation, 1=Bull, 2=High Volatility)
hmm_covariance_type: "diag" # Options: "spherical", "diag", "full", "tied"
hmm_iterations: 1000

# Trading Strategy Settings
trading_fee_percent: 0.0006 # 0.06%
# signal_map: # Map HMM states to trading signals (0=Hold, 1=Buy, -1=Sell)
#   0: -1 # State 0 -> Sell (Hypothesis: Bearish/Risk-Off)
#   1: 1  # State 1 -> Buy (Hypothesis: Bullish/Risk-On)

# signal_map: # Map HMM states to trading signals (0=Hold, 1=Buy, -1=Sell)
#   0: 0 # State 0 (Calm/Low Conviction) -> Hold
#   1: 1 # State 1 (High Vol/Momentum?, Best Avg Return) -> Buy
#   2: -1 # State 2 (Low Vol/Distribution?, Worst Avg Return) -> Sell (Changed back from 0)

signal_map: # Map HMM states to trading signals (0=Hold, 1=Buy, -1=Sell)
  0: 0 # State 0 (Low-vol, sideways/slight down) -> Hold
  1: 1 # State 1 (Mod-vol, slight up) -> Buy
  2: 0 # State 2 (High-vol, high-activity, neutral return) -> Hold (Changed from -1)

# Backtest/Forward Test Execution Settings
run_mode: "backtest" # Options: "backtest", "forwardtest"

# --- Performance Summary ---
# Total Return (%): 97.8440
# Annualized Sharpe Ratio: 1.0085
# Maximum Drawdown (%): -19.9845
# Trade Frequency (%): 1.6438
# Number of Trades: 18.0000
# ---------------------------
