# Configuration for ML Trading Strategy

# --- Data Settings ---
data_directory: "data"

# --- Data Download Settings (Used by download_data.py) ---
# API key is read from environment variable CYBOTRADE_API_KEY

# Define metrics and candles to download
# Structure: {source: [ {path: "endpoint_path", params: {key: value, ...}}, ... ]}
# VERIFY paths and parameter values (exchange, window, i, a, symbol, interval) against cybotrade.rs docs!
metrics_to_download:
  cryptoquant:
    - path: "btc/exchange-flows/inflow"
      params: { exchange: "binance", window: "day" }
    - path: "btc/market-data/funding-rates"
      params: { exchange: "binance", window: "day" }
  glassnode:
    - path: "addresses/active_count"
      params: { a: "BTC", i: "24h" }
    - path: "transactions/count"
      params: { a: "BTC", i: "24h" }
  coinglass:
    - path: "futures/openInterest/ohlc-history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1d" }
    - path: "futures/globalLongShortAccountRatio/history"
      params: { exchange: "Binance", symbol: "BTCUSDT", interval: "1d" }
  # Candle source uses a slightly different structure if needed, or can follow path/params
  candles:
     - source_override: "bybit-linear"
       path: "candle"
       params: { symbol: "BTCUSDT", interval: "1d"}


# Time periods for downloading data (Unix timestamp in milliseconds)
# Backtest Period (3 years)
backtest_start_time_ms: 1609459200000     # Jan 1 2021
backtest_end_time_ms: 1704067199000       # Dec 31 2023
# Forward Test Period (3 years)
forwardtest_start_time_ms: 1704067200000  # Jan 1 2024
forwardtest_end_time_ms: 1735689600000    # Jan 1 2025

# --- ML Model & Strategy Settings (Used by main_strategy.py) ---
# ... (rest of the config remains the same, but update data_files based on new naming) ...
# Example: Update data_files based on path/params structure
data_files:
  candles: "bybit-linear_candle"
  cryptoquant_inflow: "cryptoquant_btc_exchange-flows_inflow"
  cryptoquant_funding: "cryptoquant_btc_market-data_funding-rates"
  glassnode_active: "glassnode_addresses_active_count"
  glassnode_tx: "glassnode_transactions_count"
  coinglass_oi: "coinglass_futures_openInterest_ohlc-history"
  coinglass_lsr: "coinglass_futures_globalLongShortAccountRatio_history"

# Features to use for HMM model training (column names after data loading/preprocessing)
# Example - adjust based on actual columns and desired features
# Features to use for HMM model training (column names after data loading/preprocessing)
features:
  - "price_return"
  - "volatility"
  - "cryptoquant_funding_rate"
  - "glassnode_active_value"
  - "funding_rate_change"
  - "active_addresses_change"
  - "cryptoquant_inflow_value"
  - "coinglass_oi_value"

# HMM Settings
# Number of hidden states (e.g., 0=Bear/Consolidation, 1=Bull, 2=High Volatility)
hmm_states: 4
# Options: "spherical", "diag", "full", "tied"
hmm_covariance_type: "diag"
hmm_iterations: 1000

# Trading Strategy Settings
trading_fee_percent: 0.0006

# Map HMM states to trading signals (0=Hold, 1=Buy, -1=Sell)
signal_map:
  0: 0  # State 0 (High-vol choppy?) -> Hold
  1: 1  # State 1 (Low-vol up?) -> Buy
  2: 0  # State 2 (Bearish/Downtrend?) -> Hold (Changed back from -1)
  3: 1  # State 3 (Strong momentum up?) -> Buy (Changed from 0)
  # 2: -1 # State 2 (Bearish/Downtrend?) -> Sell (Changed from 0)

# Backtest/Forward Test Execution Settings
# Options: "backtest", "forwardtest"
run_mode: "backtest"
# run_mode: "forwardtest"

# --- Performance Summary ---
# Total Return (%): 97.8440
# Annualized Sharpe Ratio: 1.0085
# Maximum Drawdown (%): -19.9845
# Trade Frequency (%): 1.6438
# Number of Trades: 18.0000
# ---------------------------

# --- Performance Summary ---
# Total Return (%): 308.8723
# Annualized Sharpe Ratio: 1.1167
# Maximum Drawdown (%): -51.1727
# Trade Frequency (%): 5.0228
# Number of Trades: 55.0000
# ---------------------------

# --- Performance Summary ---
# Total Return (%): 109.1120
# Annualized Sharpe Ratio: 0.8237
# Maximum Drawdown (%): -35.7398
# Trade Frequency (%): 4.4749
# Number of Trades: 49.0000
# ---------------------------
